#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("IsaLightCat.Resource", IsApplication=true)]

namespace IsaLightCat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::IsaLightCat.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::IsaLightCat.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::IsaLightCat.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::IsaLightCat.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::IsaLightCat.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::IsaLightCat.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::IsaLightCat.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::IsaLightCat.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::IsaLightCat.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::IsaLightCat.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::IsaLightCat.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::IsaLightCat.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::IsaLightCat.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::IsaLightCat.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::IsaLightCat.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::IsaLightCat.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::IsaLightCat.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::IsaLightCat.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::IsaLightCat.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::IsaLightCat.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::IsaLightCat.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::IsaLightCat.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int isa_cat_close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int isa_cat_open = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int OptionHostName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int OptionPort = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int OptionRemoteServer = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int OptionsButton = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int ResultFullName = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int ResultMessage = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int ResultResultState = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int ResultRunSingleMethodTest = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int ResultStackTrace = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int ResultsFailed = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int ResultsId = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int ResultsIgnored = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int ResultsInconclusive = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int ResultsMessage = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int ResultsPassed = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int ResultsResult = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int RunTestsButton = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int TestSuiteListView = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int imageButton = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int options = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int results = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_result = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int test_suite = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int tone_cat_meow = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int tone_cat_meow2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tone_cat_meow3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tone_cat_meow4 = 2131034115;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
